development:
  adapter: postgresql
  encoding: unicode
  database: mango_dev
  pool: 5
  host: localhost
  username: ''
  password: ''

test:
  adapter: postgresql
  encoding: unicode
  database: mango_test
  pool: 5
  username: ''
  password: ''